### ISSUE TITLE
source_id MCM-UA-1-0 change of license agreement

### ISSUE THREAD

**Issue by rjstouffer** [WCRP-CMIP/CMIP6_CVs#1075]
Changing the agreement to CC BY 4.0 is fine for the MCM-UA-1-0 model and data.

-Ron Stouffer

**Comment by rjstouffer** [comment]
HI Paul,

Our email crossed.

Are you happy with the GEOS-CMIP@ address for contacts?  YES

And what date would you like the CC BY 4.0 relaxation to be set? According
to our archive, the first published date of MCM-UA-1-0 was 2019-07-31 Any
time suits me. July 31, 2019 is fine.

-Ron

**Comment by durack1** [comment]
@rjstouffer that change is now in place, upon reflection as no license waiver appears to have been granted to date, I assigned today's date as the change (rather than retrospectively dating this). You can see the revised details at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and this will propagate across the ESGF and citation pages overnight
