### ISSUE TITLE
E3SM v2 Regional Refined Mesh (RRM) Configuration Registration

### ISSUE THREAD

**Issue by chengzhuzhang** [WCRP-CMIP/CMIP6_CVs#1179]
Hi @durack1 , not sure if this is best place to for this discussion. But you have been always so responsive here. I will just go ahead :)

E3SM project is looking into submit E3SM v2 with the RRM configuration over North America.  The NARRM features finer horizontal resolution grids centered over NA, consisting of 25→100 km atmosphere and land, 0.125° river routing model, and 14→60 km ocean and sea ice. So far, E3SM only contributed regular lat-lon data to CMIP and I haven't been able to find an existing example from other modeling centers who also submitted a similar configuration. I know that to remapping to a universal 1 degree or 0.25 degree might be options. But I'm wondering if there is any guidance from CMIP to accommodate this type of configuration.  Thank you. Tagging @tangq for this discussion. He leads the RRM effort at E3SM.

**Comment by matthew-mizielinski** [comment]
Hi @chengzhuzhang ,  I know of one group who have published unstructured data to CMIP6 (have a look at `CMIP6.HighResMIP.AWI.AWI-CM-1-1-HR.hist-1950.r1i1p1f2.Omon.tos.gn.v20190825`), but note that users would need to be able to work out how to use it -- a quick look with ncview at this data set isn't intuitive due to the nature of UGRID file structure (separate plotting tools required).

In your position I'd consider regridding to a grid with local refinement in rows and columns (i.e. smaller delta lon and delta lat for corresponding rows/columns for north America) -- you'll end up with some unusual grid cell shapes, i.e. a larger dlat:dlon aspect ratio, but I would guess that many tools would cope (might be worth testing first). If you choose this option I strongly recommend some nice clear documentation pages as users will find this unusual at least.

I can imagine that it would also be possible to use 2D coordinates (as used in the ORCA ocean grids), but I suspect that there would need to be large areas of masked data to keep a reasonably logical structure. I could see this causing data users some concern, particularly those using low level tools to view data (it would look very weird in ncview for example).

**Comment by taylor13** [comment]
Regarding @matthew-mizielinski 's 2nd paragraph suggestion, if I understand it correctly, you will report data at higher resolution than simulated at all latitudes and longitudes that intersect North America but lie outside that region.  This is a result of imposing a logical 2-d coordinate system and does preserve the high resolution over N. America at the expense of increasing the size of data arrays (and, incidentally, perhaps misleading folks as to model resolution outside N.A.).  Still, this might be the best option for serving researchers.  

Another idea I haven't thought about too much is to regrid to a latxlon grid but with the N. pole rotated to lie over N. America and with non-uniform latitude spacing that decreases (nonlinearly) near the rotated pole.  This would provide high resolution over N. America and lower resolution elsewhere and would be logically 2-D.

**Comment by tangq** [comment]
Most of our analysis tools prefer regular lat-lon grids with some have the capability to use the irregular native grids. For the overview paper, I regridded the data with NCO to two lat-lon grids (global 1 degree and regional (North American) 0.25 degree). The native grid is a 1D coordinate system. I am not sure which method would be optimal. Some basic knowledge about the RRM grid is required for users not to misuse the data.

**Comment by durack1** [comment]
@chengzhuzhang thanks for raising this query. Just circling around to figure out where this is at currently.

It would make sense that a new model is registered if you have a different grid configuration, and differing results from the other v1, v1-1 and v2 configurations. Having said that, I also agree with @tangq, there is little point in publishing data if it's not readily usable, so some data massaging into a "standard" format will likely be required to make this usable

**Comment by chengzhuzhang** [comment]
Sorry for getting back late. I just add a chance to talk with @tangq on potential path forward. We were wondering if @matthew-mizielinski could provide some guidance on the second suggestion in this comment: https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1179#issuecomment-1348129917 so that we can follow and test the method. Our cmorization tool might need to be revised accordingly for irregular lat lon grids..

Alternatively, it perhaps is fine to report data at two resolutions (i.e., 1 degree and 0.25 degree) globally. We will provide documentation on the native grids such as figure 1 of this paper to guide users: https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1179#issuecomment-1348129917. If we follow this approach, does this mean that we have to have two registration to CMIP6_CVs?

**Comment by durack1** [comment]
@chengzhuzhang the logic is that every unique **original** model configuration is what is registered in the CVs, and then if a non-native grid is used to write out the data, then a non-native **grid_label** is used - so native grid data has the `grid_label = gn`, whereas a regridded output would be identified by a `gr, gr1, gr2` etc identifier - see descriptors in https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_grid_label.json. In the case that both a 1deg and 0.25deg output was written, this could be labelled `gr` and `gr1` respectively - with the preferred target grid using the `gr` identifier

**Comment by durack1** [comment]
For an example of how many of the tripolar grids look, the plot below shows the ocean area fraction for the ACCESS1-0/CMIP5 model, where the grid telescopes across latitudes, low res at hi lats, higher res at midlats to the tropics and back down to low res again (from https://github.com/CDAT/cdat/issues/402#issuecomment-141268439)
![issue_402_output](https://cloud.githubusercontent.com/assets/3229632/9948364/34a3c2ba-5d57-11e5-99a8-e0c08d7916c3.png)

**Comment by chengzhuzhang** [comment]
@durack1 and @matthew-mizielinski thank you for chiming in. Although Matt's diagram makes good sense to me, it feels like a sizeable project to sort out the regriding in practice and make sure the result will fall in to standard and not confuse the users...

The flexibility Paul brought up to report one configuration with multiple grids actually is more practical to fit into our current post-processing workflow. @tangq and I just discussed that we could report the unstructured data with `gn`, and `gr` for globally 0.25 degree remapped data and `gr1` for 1 degree. In this case, is there a way to also publish grids/mapping files through ESGF? Otherwise we can provide a link in the metadata for accessing the files.

**Comment by chengzhuzhang** [comment]
The team made a decision on reporting data remapped to global 1 degree: https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1190. I will close this PR for now.

**Comment by durack1** [comment]
@chengzhuzhang no problem, thanks for the update. If the model native configuration differs from the existing registered configs ([`E3SM-1-0`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2284-L2347), [`E3SM-1-1`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2348-L2409), [`E3SM-1-1-ECA`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2410-L2468),  [`E3SM-2-0`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2469-L2529)), then it would be best to register a new configuration.

You can also identify that you are not writing out native format data, by using the preferred target grid identifier `gr` identifier (rather than `gn` which denotes native grid output - see [CMIP6_grid_label.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_grid_label.json)). This will mean folks don't confuse differing results due to model configuration differences not being identifiable in the model source_id.
