### ISSUE TITLE
GISS-E2-1-G-CC: activity_id -- add 'ScenarioMIP' ; GISS-E2-2-H:  activity_id -- add 'CFMIP' 

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#1207]
GISS-E2-1-G-CC: C4MIP CMIP (ScenarioMIP missing)
GISS-E2-2-H: CMIP SIMIP ScenarioMIP (CFMIP missing)

**Comment by durack1** [comment]
@gavinny perfect, will get these updates in the queue soon, thanks

**Comment by durack1** [comment]
@gavinny that should now be fixed in [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) (and the CVs where publications are being validated). I'll wait for a sync and then see if we can kick start this local replication/republication process to see if we're back in business
