### ISSUE TITLE
activity_ids missing for NCAR

### ISSUE THREAD

**Issue by strandwg** [WCRP-CMIP/CMIP6_CVs#1208]
Please add the following activity_ids

PMIP.NCAR.CESM2-FV2
ScenarioMIP.NCAR.CESM2-FV2

Thanks!

**Comment by durack1** [comment]
@strandwg adding

PMIP.NCAR.CESM2-WACCM-FV2.lgm

**Comment by durack1** [comment]
@strandwg that should now be fixed in [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) (and the CVs where publications are being validated). I'll wait for a sync and then see if we can kick start this local replication/republication process to see if we're back in business
