### ISSUE TITLE
Update institution_id and source_id to reflect WGCM-20 documents

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#155]
Update `institution_id` and `source_id` entries with those proposed in the [WGCM-20 meeting notes](https://www.wcrp-climate.org/modelling-wgcm-meetings/64-unifying-themes/unifying-themes-modelling/modelling-wgcm/modelling-wgcm-sessions/1027-wgcm20-presentations). In particular the notes under [Participating CMIP6 Model Groups](https://www.wcrp-climate.org/images/modelling/WGCM/WGCM20/documents/3b_Eyring_CMIP6Overview_WGCM_161101.pdf#page=9)

**Comment by durack1** [comment]
@MartinaSt these links are the most up-to-date information that I have seen.. The numbers underlying the [page 7](https://www.wcrp-climate.org/images/modelling/WGCM/WGCM20/documents/3b_Eyring_CMIP6Overview_WGCM_161101.pdf#page=7) table are what you want as a first pass

**Comment by durack1** [comment]
@MartinaSt I have pulled your email inline here so it doesn't get lost
```
From: Martina Stockhause
Date: Thursday, December 15, 2016 at 12:29 AM
To: Paul Durack, "Taylor, Karl E."
Subject: Re: [WCRP-CMIP/CMIP6_CVs] Update institution_id and source_id to reflect WGCM-20 documents (#155)

Hi Paul, hi Karl,

I would like to come back to our discussion about how to get the required input for the data citation:

1. required - list of data citation managers:
The best way to collect such small bit of information is normally an integration in already existing information. Thus: Would it be possible to have a sort of "responsible person" in the CV of the source_id, which I could use either directly as citation manager or at least as contact person to ask about the citation manager?
What do you think?

2. nice to have - list of MIPs per model:
Thanks for the link, Paul. And yes, the underlying information of the table was what I asked for.
You do not plan to have an activity_id list in the CV for the source_id similar to the institute_id list?
That would be ideal for me. If that is not planned, I would offer all combinations for institute_ids, source_ids and activity_ids for the citation managers in our application. If they don't supply authors for some of the entries because they do not participate in some of the MIPs, that does not harm and I don't think the additional unused entries will cause just minor irritations but no confusion.

Thanks and best wishes,
Martina
```

To answer your question, for each issue that lists a new `source_id` to be registered, we have the github handle of the contributor - this is not an ideal entry, but it does provide a method for contacting the responsible party. I wonder if ES-DOCs have a "citation manager" that they're listing as the contact - @eguil?

**Comment by taylor13** [comment]
I have sent an email to the modeling groups asking for POCs for the data citation information.  I don't think the POCs are needed for other parts of CMIP, so there is no reason to have them register at PCMDI.  Here's the text of the email sent out:

  Dear CMIP6 Modeling Group Contacts,

As part of the terms of use for CMIP6 model output, users are obliged to cite CMIP6 data when it is used in publications (see https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html).  A web-based service has been set up to associate with each dataset in the CMIP6 archive the appropriate citation information. Data users will be able to access citation information via the ESGF portal and the further_info_url global attribute in the netCDF files.

Someone at your institution must be responsible for entering and maintaining citation information in the citation GUI http://cera-www.dkrz.de/citeXA .  With this email we request the following contact information for that individual (so that an account can be set up):

* Person: name, email, ORCID (if available), affiliation and
* Specification of the data, for which this person is responsible, according to the Controled Vocabulary (https://github.com/WCRP-CMIP/CMIP6_CVs ): source_id and institute_id

 Send this information to Martina Stockhause (stockhause@dkrz.de) who can also answer any questions you have.

Please note that before your account can be set up you must also register your institution and model(s) following the instructions at the bottom of the following webpage: https://github.com/WCRP-CMIP/CMIP6_CVs

Best regards,
Karl Taylor and V. Balaji
co-chairs of the WGCM Infrastructure Panel (WIP) 

I think this issue can now be closed.

**Comment by durack1** [comment]
@taylor agreed, I will close
