### ISSUE TITLE
institution_id registration of THU

### ISSUE THREAD

**Issue by yjyangjie** [WCRP-CMIP/CMIP6_CVs#225]
institution_id = THU
institution = Department of Earth System Science,Tsinghua University, Beijing 100084, China

**Comment by davidhassell** [comment]
Hello,

My name is David Hassell and I am part of the ES-DOC team that is working on CMIP6 documentation. As a part of this process, we need a liaison at THU who can act as the interface between the scientists who actually provide the documentation and the ES-DOC team. I was wondering if you are able to help with identifying such a person?

The documentation process has changed considerably since CMIP5 (in response to the feedback that we received), and you can now choose from a variety of documentation methods. Our aim is to train the ES-DOC liaison who can then work with people at THU. No specialist knowledge about ES-DOC nor climate modelling is required, but neither would it be a problem, of course. Some institutes have appointed a member of the modelling team, others not.

I would be very grateful f you could let me know by e-mail (david.hassell at ncas.ac.uk) if you have any suggestions.

All the best,

David Hassell

National Centre for Atmospheric Science
University of Reading
UK
