### ISSUE TITLE
frequency augment format with identifiers

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#342]
Along with #166, a request has been received to augment the `frequency` CVs with identifiers as below:
```
"frequency":{
 "1hr":"1-hourly average",
 "1hrClimMon":"1-hourly climatological average",
 "3hr":"3-hourly average",
 "6hr":"6-hourly average",
 "day":"daily average",
 "dec":"decadal average (calculated as the mean of 10 years and 12 months per year)",
 "fx":"fixed (time-invariant)",
 "mon":"monthly average",
 "monClim":"monthly climatological average (climatological period should be defined)",
 "subhr":"???",
 "yr":"annual average",
 "yrClim":"annual average (climatological period should be defined)"
},
```
Suggested amendments or improvements to the suggested values above are welcomed

**Comment by taylor13** [comment]
Note: At some frequencies (e.g., 6hr and 3 and possibly 1hr) some variables may be recorded synoptically (so-called "point" data) while others are time-means at some frequencies, so the descriptions will have to be modified.

Is the idea that the abbreviations are not easy to understand?  If so, perhaps they should be written: 

    "1hr":"sampled hourly"
    "1hrClimMon":"monthly climatology of diurnal cycle computed from hourly samples" 
    "3hr":"sampled every 3 hours"
    "6hr":"sampled every 6 hours"
    "day":"daily mean samples"
    "dec": **** are you sure these resolve the annual cycle? I thought they were simply decadal means, so they would be labeled "decadal mean samples".
    "fx":"fixed (time invariant) field"
    "mon":"monthly mean samples"
    "monClim":"monthly climatology computed from monthly mean samples"
    "subhr":"sampled sub-hourly"
    "yr":"annual mean samples"

 In the current data request there are no instances of yrClim.  Unless this is an error in the data request, yrClim  should be removed from the CV.  Otherwise I would describe it as "multi-year time mean"

**Comment by durack1** [comment]
@dnadeau4 the change [noted above](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/342#issuecomment-307144444) will likely be implemented today, it'd be great to get this into the new [`cmip6-cmor-tables/Tables/CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L927-L941) release, so just a change to the script that generates the json file
