### ISSUE TITLE
institution_id registration of SNU

### ISSUE THREAD

**Issue by sjh11556** [WCRP-CMIP/CMIP6_CVs#386]
institution_id = SNU
institution = Seoul National University, Seoul 08826, Republic of Korea

**Comment by davidhassell** [comment]
Hello,

My name is David Hassell and I am part of the ES-DOC (​​https://es-doc.org/) team that is working on CMIP6 documentation. As a part of this process, we are looking for a liaison at SNU who can act as the interface between the many scientists who actually provide the documentation and the ES-DOC team.

The documentation process has changed considerably since CMIP5​ ​in response to the feedback that we received. Our aim is to train the ES-DOC liaison who can then work with people at SNU to facilitate the production of documentation for the whole CMIP6 process​. No specialist knowledge ​of ES-DOC or climate modelling is required, but neither would it be a problem, of course. Some institutes have appointed a member of the modelling team, others not.

The model documentation phase will be starting soon, and having a liaison in place should make the process run more smoothly.

I would be very grateful if you could let me know by e-mail (david.hassell at ncas.ac.uk) if you have any suggestions

All the best,

David Hassell and Eric Guilyardi
On behalf of the ES-DOC team

National Centre for Atmospheric Science
Department of Meteorology, University of Reading
