### ISSUE TITLE
institution_id registration of HAMMOZ-Consortium

### ISSUE THREAD

**Issue by nedavid** [WCRP-CMIP/CMIP6_CVs#402]
institution_id = HAMMOZ-Consortium
institution = ETH Zurich, Switzerland, Max Planck Institut für Meteorologie, Germany, Forschungszentrum Jülich, Germany, University of Oxford, UK, Finnish Meteorological Institute, Finland, Leibniz Institute for Tropospheric Research, Germany, Center for Climate Systems Modeling (C2SM) at ETH Zurich, Switzerland

**Comment by davidhassell** [comment]
Hello,

My name is David Hassell and I am part of the ES-DOC (​​https://es-doc.org/) team that is working on CMIP6 documentation. As a part of this process, we are looking for a liaison at HAMMOZ-Consortium who can act as the interface between the many scientists who actually provide the documentation and the ES-DOC team.

The documentation process has changed considerably since CMIP5​ ​in response to the feedback that we received. Our aim is to train the ES-DOC liaison who can then work with people at HAMMOZ-Consortium to facilitate the production of documentation for the whole CMIP6 process​. No specialist knowledge ​of ES-DOC or climate modelling is required, but neither would it be a problem, of course. Some institutes have appointed a member of the modelling team, others not.

The model documentation phase will be starting soon, and having a liaison in place should make the process run more smoothly.

I would be very grateful if you could let me know by e-mail (david.hassell at ncas.ac.uk) if you have any suggestions

All the best,

David Hassell and Eric Guilyardi
On behalf of the ES-DOC team

National Centre for Atmospheric Science
Department of Meteorology, University of Reading

**Comment by durack1** [comment]
@nedavid it seems that @mbittner1 is no longer our contact for MPI-M. Can you please send me an email (add @llnl.gov to by github handle) so we can capture your full contact information correctly?

@taylor13 @MartinaSt @davidhassell ping!
