### ISSUE TITLE
Experiment ID: "LAND" & "BGC" ??

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#423]
This from SENESI Stéphane:
```
The experiments list at http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master
/src/CMIP6_experiment_id.html is a reference for the basic document (DRS et al.) at
 https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit

The list includes a number of experiments with LAND as the single required component,
 and with no additional allowed component. Because some of these experiment do not 
necessarily include the BGC component, and because the CV that defines source types (at 
 https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_type.json) 
does not specify that LAND implicitly includes BGC, I feel that there is some ambiguity

It could be clearer to :
    - keep source type CV unchanged
    - allow BGC as an additional component for all experiments requiring the LAND component (at 
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_type.json)
    - require BGC as a component for those experiments which obviously need it, as e.g. 
land-cCO2

The other way would be to :
    - change the source type CV to state that LAND source type includes BGC component
    - allow models without a BGC component in LAND to hide that fact
```
I will write to the LUMIP folks and ask them to comment.

**Comment by senesis** [comment]
LS3MIP and/or LUMIP leaders should decide, for all experiments today described as having only the LAND component, which should have BGC as an allowed component, and which should have BGC as a required component

**Comment by taylor13** [comment]
Yes, I've now written them and will record their response(s) below.

**Comment by dlawrenncar** [comment]
Hi all (I've also put this response onto github),

There is ambiguity here because these experiments are addressing several different questions.  Note that in general, the goal is for groups to run the key experiments (e.g., land-hist, land-future, land-noLu) with the same version of the land model that is used in the coupled model.  In an ideal world, groups would also run all the other experiments with this same version of the model.  However, we anticipated in LUMIP paper that some land modeling groups would have (at least) 2 versions of their model (a more stripped down one that is used in coupled model simulations and a more advanced version, e.g. with detailed land management processes, that would be used mostly in land-only simulations).  In these situations, groups are supposed to do the key experiments as I listed above with the coupled model version (BGC or not BGC, depending on the model) and then are free to submit a second set of simulations with their advanced land model.  So ... confusing. 

To answer your specific question.  The following expts could be usefully run with or without BGC.

land-future
land-hist-cruNcep
land-hist-princeton
land-hist-wfdei
land-hist
land-noLu

Some of the remaining runs could technically be run without BGC, but the experiments were not really designed to be run without BGC so I think it would be fine to put a 'requirement' for BGC for these runs.

land-cClim
land-cCO2
land-crop-grass
land-crop-noFert
land-crop-noIrrig
land-crop-noIrrigFert
land-hist-altLu1
land-hist-altLu2
land-hist-altStartYear
land-noFire
land-noPasture
land-noShiftCultivate
land-noWoodHarv

Regards,

Dave

**Comment by durack1** [comment]
For the changes above, the first block `land-future` should have:
```
        "land-future":{
...
            "additional_allowed_model_components":"BGC",
...
            "required_model_components":[
                "LAND"
            ],
...
```
and for the `land-cClim` block
```
        "land-future":{
...
            "additional_allowed_model_components":"",
...
            "required_model_components":[
                "LAND",
                "BGC"
            ],
...
```
@taylor13

**Comment by durack1** [comment]
@eguil @davidhassell @charliepascoe @momipsl the proposed changes will likely need to be updated downstream in ES-DOC land

**Comment by durack1** [comment]
@dlawrenncar @senesis those changes are now made. Please take a peek at [CMIP6_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json) and [hCMIP6_experiment_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) to make sure changes are correct
