### ISSUE TITLE
institution_id registration of CAS

### ISSUE THREAD

**Issue by yongqiangyu** [WCRP-CMIP/CMIP6_CVs#426]
institution_id = CAS
institution = Chinese Acadamy of Sciences, Beijing 100029, China

**Comment by davidhassell** [comment]
Hello,

My name is David Hassell and I am part of the ES-DOC (​​https://es-doc.org/) team that is working on CMIP6 documentation. As a part of this process, we are looking for a liaison at CAS who can act as the interface between the many scientists who actually provide the documentation and the ES-DOC team.

The documentation process has changed considerably since CMIP5​ ​in response to the feedback that we received. Our aim is to train the ES-DOC liaison who can then work with people at CAS to facilitate the production of documentation for the whole CMIP6 process​. No specialist knowledge ​of ES-DOC or climate modelling is required, but neither would it be a problem, of course. Some institutes have appointed a member of the modelling team, others not.

The model documentation phase will be starting soon, and having a liaison in place should make the process run more smoothly.

I would be very grateful if you could let me know by e-mail (david.hassell at ncas.ac.uk) if you have any suggestions

All the best,

David Hassell and Eric Guilyardi
On behalf of the ES-DOC team

National Centre for Atmospheric Science
Department of Meteorology, University of Reading

**Comment by yongqiangyu** [comment]
Dear David and Eric,

Thank you for your message! 

Weipeng Zheng (zhengwp@mail.iap.ac.cn <mailto:zhnegwp@mail.iap.a.cn> ) and I (yyq@lasg.iap.ac.cn <mailto:yyq@lasg.iap.ac.cn> ) will be responsible for the CAS model documentation process, and we are going to provide necessary information of CAS climate models as required by CMIP6.

Best wishes,

Yongqiang
_______________________________
Dr. Yongqiang Yu
LASG, Institute of Atmospheric Physics
Beijing 100029, China
Tel: 86-10-82995167 Fax: 86-10-82995172
http://www.escience.cn/people/yuyongqiang/index.html
