### ISSUE TITLE
Clarifying model components for AerChemMIP experiments

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#438]
The following email was received today, appending below for reference
```
From: MICHOU Martine
Date: Tuesday, November 21, 2017 at 1:32 AM
To: "Taylor, Karl E.", Bill Collins, Michael Schulz
Cc: "Durack, Paul J.", SENESI Stéphane, NABAT Pierre
Subject: CMIP6 exp id page

Dear all,

In the http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html page
for AerChemMIP a number of simulations indicate BGC in the "additional allowed model components" column  while other do no indicate BGC, see for instance for the histSST-piCH4 simulation.  
We believe that AerChemMIP simulations should all have the same AER, CHEM, and BGC components listed either in the "Required" column or in the "Additional" column. Thank you for the amending the web page if this is agreeable to you or let us know why it should not be the case.

Regards,
Martine Michou

----- Météo-France -----
MICHOU MARTINE
CNRM/GMGEC/AMACS 
XX.xx@meteo.fr 
Fixe : +33 561079xxx
```
@MartineMichou @taylor13 @wjcollins @senesis please reply to this issue, so we can keep a track of the resolution within this repo and out of inboxes

**Comment by wjcollins** [comment]
Yes, I agree. The "additional allowed model components" should include all of AER, CHEM and BGC that are not listed in "required model components".

**Comment by taylor13** [comment]
I apologize for the delay in getting back to you on this.  I think early on we reserved the use for "BGC" with coupled models (because it was assumed that if you had an AGCM simulation with prescribed SSTs, you wouldn't be keeping track of carbon fluxes and so your BGC component would be inactive). If a model component that keeps track of biogeochemical fluxes and reservoirs is included in an atmosphere-only simulation, then we should allow "BGC" as an optional component of a fixed SST simulation.  There are many CMIP6 endorsed MIP experiments that include "BGC" as an optional experiment in AGCM fixed SST experiments, but the DECK AMIP standard run doesn't include "BGC" as an option.  

I recommend (if there are no objections) that for all AerChemMIP experiments and also for the DECK AMIP experiment we include "BGC" as an optional model component.  (Note: "AER" and "CHEM" are already included in all the AerChemMIP experiments.)

**Comment by wjcollins** [comment]
Fine by me.

**Comment by taylor13** [comment]
@durack1 For the AerChemMIP experiments and for the DECK AMIP experiment, please add to the experiment_id CV "BGC" whenever it is missing in the list of "additional allowed components" if it isn't already listed under "required model components".  Or do you want me to do that?

**Comment by durack1** [comment]
@MartineMichou @taylor13 @wjcollins @senesis those changes are now in place, please take a peek at [CMIP6_experiment_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) to validate the new entries and let me know if any further tweaks are required
