### ISSUE TITLE
How to get a valid tag from CMIP6_CV git repository clone ?

### ISSUE THREAD

**Issue by senesis** [WCRP-CMIP/CMIP6_CVs#448]
I would like to document data produced for CMIP6 by a tag for the CMIP6_CV version

When using `git describe HEAD` (which I believe is the right way to do) on a CMIP6_CV repository clone, I get value : 
`3.2.7-85-gd2499a2`

This seems to be not in line with the set of tags of this repository, which includes for instance `3.3.0` and `CMOR-3.3.0`

So, how to get a version's reference tag ?

**Comment by durack1** [comment]
@senesis apologies for the delay in reply.

You've uncovered an unusual quirk with git that returns the latest `annotated` tag only when issuing a `git describe HEAD`. The latest tag in the repo is currently `3.3.0/CMOR-3.3.0`, see below:
```
[duro:git/CMIP6_CVs] duro% git tag
3.2.0
3.2.1
3.2.2
3.2.3
3.2.4
3.2.5
3.2.6
3.2.7
3.2.8
3.3.0
CMOR-3.2.5
CMOR-3.2.7
CMOR-3.2.8
CMOR-3.3.0
```
The issue you've described will likely only be solved if we clean up all the existing tags, and rewrite these all as `annotated` tag types. While we're planning to do this, can you give us a short while so that we can synchronize the tag notation across related projects.

@dnadeau4 @doutriaux1 @taylor13  @sashakames pinging you all on this

**Comment by durack1** [comment]
For reference:
https://stackoverflow.com/questions/21738647/change-date-of-git-tag-or-github-release-based-on-it
https://stackoverflow.com/questions/6900328/git-command-to-show-all-lightweight-tags-creation-dates

**Comment by senesis** [comment]
I can use a hard coded value for the time being, and use `git describe HEAD` as soon as you will put a new (annotated) tag, e.g. for version 3.3.1

**Comment by durack1** [comment]
To resolve this issue, we'll implement the changes in #28. This will require the existing tags to be renamed using the notation `6.2.0.x`, with `x` being an integer 1-10 covering the existing tags `3.2.0-3.3.0`, and an annotated tag type being used which will capture the previous tag name (e.g. `3.2.5/CMOR-3.2.5`) so that a verbose tag listing (with annotations for each tag) will provide connection with the previous tags.

@dnadeau4 @taylor13 do you have anything to add here?

**Comment by dnadeau4** [comment]
I will annotate the tags in the [cmip6_table_repository](https://github.com/PCMDI/cmip6-cmor-tables/releases).  The last 2 digits will be martin's DRQ tag so 
`3.3.0.20` will be `CMOR-3.3.0` using `DRQ 01.00.20`.

I will describe this in the README file. 

When you change you CMIP6_CVs,  a new pull request and merge will happen at midnight, but no tag will be created.  People who needs the new source/insitution will have to do a `git pull --all -p`
 
Sounds good?

**Comment by durack1** [comment]
@dnadeau4 that sounds good, you've also been pulling across the version info into CMIP6_CV.json so that will provide some connectivity between the repo statuses

**Comment by durack1** [comment]
For use in retagging:
```
[duro:sync/git/CMIP6_CVs] duro% git show-ref --tags
5c4bbac517cb2053c6d43957d552cd435809055a refs/tags/3.2.0
f5b0ef598a110f60a474f1f271b54ee2b417ee0d refs/tags/3.2.1
511ab24b89bedbb242e0783a7815670ceab349bd refs/tags/3.2.2
41fd650dd7b79b74783dd587b3103582d7934a82 refs/tags/3.2.3
b48ad53b379141b22ed833fa39d9902b5c2ffe2e refs/tags/3.2.4
8537f933f1b658f9e23251710a1bfd820c8f2594 refs/tags/3.2.5
a4f9cf0dfb3be62a2d0daf09b3e9e3512a887196 refs/tags/3.2.6
df18ec966ba2c5dfa2d446010395a40a1ac05d7e refs/tags/3.2.7
3bbbc883bfaf7a8f99cd50603bbf3199491d7c49 refs/tags/3.2.8
bb42f99cd16b72929fad46d068de922cadcb4db2 refs/tags/3.3.0
8537f933f1b658f9e23251710a1bfd820c8f2594 refs/tags/CMOR-3.2.5
0a87d44c7137f234b22ddef01083097ecf575eb9 refs/tags/CMOR-3.2.7
3bbbc883bfaf7a8f99cd50603bbf3199491d7c49 refs/tags/CMOR-3.2.8
bb42f99cd16b72929fad46d068de922cadcb4db2 refs/tags/CMOR-3.3.0
```

**Comment by durack1** [comment]
@senesis those changes are now implemented, `git describe HEAD` still reports an erroneous `6.2.0.10-8-gc1e8ffa`.

The latest tag is `6.2.0.11`:
```
[duro:CMIP6_CVs] duro% git show-ref --tags
feb687c1e0fa1ba65ca921d3c716d43675c8eb8c refs/tags/6.2.0.1
7f2d994fc893dc20a78fcb6d8a4093257e1a6611 refs/tags/6.2.0.10
3f41a03113b0638fa76427136c7fea47d5a5cee8 refs/tags/6.2.0.11
ddbcbec24fd59fe560be64505b249306bfd1c97c refs/tags/6.2.0.2
11a37a2e2a5c07cd8032cfe24c27fdeb2a30ddb3 refs/tags/6.2.0.3
4029f447a78c623b4f4c20c03b1d2a1eb0eb3afa refs/tags/6.2.0.4
593e5f25a5560530c35bc54ab07a89d869a20f07 refs/tags/6.2.0.5
3f9d96b25648cf3b6718ae3429466957d1d8510e refs/tags/6.2.0.6
c3e71c067ccd9c6ba29a0cd2f2831d7a6e748212 refs/tags/6.2.0.7
bd9e22142513c82b47f1132d9d209179f99f7866 refs/tags/6.2.0.8
6b2bc7bc3bf98f7578469cb89df62dbb05ca83ad refs/tags/6.2.0.9
```
@taylor13 @dnadeau4
