### ISSUE TITLE
experiment_id CDRMIP experiment length discrepancies

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#594]
```
From: Charlotte Pascoe
Date: Thursday, August 2, 2018 at 4:38 AM
To: dkeller@xxx, "Taylor, Karl E.", "Durack, Paul J."
Subject: CDRMIP experiment length discrepancies

Hi Karl, Paul and David 

I have found some discrepancies to do with the length of the CDRMIP experiments as 
described in CDRMIP GMD paper and the info about the CDRMIP experiments in the 
info table at PCMDI.

The CDRMIP GMD paper states a branch time and the minimum number of years.  For 
the experiments listed below the minimum number of years in the GMD paper is 
generally one year less than the minimum number of years in the PCMDI table. The 
exception being esm-ssp585-ocn-alk which is listed as 81 years at PCMDI and 65 
years in the CDRMIP GMD paper.

experiment: PCMDI temporal constraint, GMD temporal constraint
esm-ssp534-over: 2015-2100 86yrs, 2015-2099 85yrs
esm-ssp585-ocn-alk: 2020-2100 81yrs, 2020-2084 65yrs
esm-ssp585-ocn-alk-stop: 2070-2100 31yrs, 30yrs
esm-ssp585-ssp126Lu-ext: 2100-2300 201yrs, 2100-2299 200yrs 
esm-ssp585ext: 2100-2300 201 yrs, 2100-2299 200yrs
yr2010CO2: 2010-2105 106yrs, 2010-2104 105yrs
esm-yr2010CO2-control: 1850-2115 266yrs, 1850-2114 265yrs
esm-yr2010CO2-noemit: 2010-2105 106yrs, 2010-2104 105yrs
esm-yr2010CO2-cdr-pulse: 2010-2105 106yrs, 2010-2104 105yrs
esm-yr2010CO2-CO2pulse: 2010-2106 106yrs, 2010-2104 105yrs

PCMDI info table: https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html  
CDRMIP GMD paper: https://doi.org/10.5194/gmd-2017-168

Charlotte

-- 
Senior Data Scientist
National Centre for Atmospheric Science
Centre for Environmental Data Analysis
STFC Rutherford Appleton Laboratory
Harwell Science and Innovation Campus
OX11 0QX
Tel: +44 1235 445xxx
```
@taylor13 @momipsl @davidhassell @charliepascoe

**Comment by taylor13** [comment]
since the esm-ssp585 ends in 2100, esm-ssp585ext and esm-ssp585-ssp126Lu-ext should probably begin in 2101 and end in 2300 (200 yrs).
We had David Keller check our values here: https://docs.google.com/spreadsheets/d/1oVxksz9v268VMLetxDtOSguRh9RLMLdo8D9XKHsHDko/edit#gid=1835302454 (you can look at earlier versions there to see where he made some edits).  Should we ask him to check again?  I think he didn't realize in the GMD paper that we want the experiments to go through the final year listed, so he had 1 too few years for several experiments.

**Comment by durack1** [comment]
Folks, David is away until the 20th August, so let's wait to confirm all the `CDRMIP` details before making any changes

**Comment by dpkeller14** [comment]
Hi everyone,  I just checked and what is in the PCMDI table is correct.  In the paper there is 1 too few years for several experiments.  There is also an error for the esm-ssp585-ocn-alk experiment which should be 81 years long not 65.  Karl is also correct that since the esm-ssp585 ends in 2100, esm-ssp585ext and esm-ssp585-ssp126Lu-ext should probably begin in 2101 and end in 2300 (200 yrs).  Sorry for these discrepancies.  I will have the paper corrected and contact people on the CDRMIP mailing list to let them know about these issues.

**Comment by durack1** [comment]
Thanks @dpkeller14, so to clarify the needed changes in information stored in the CMIP6_CVs `experiment_id.json` are below:

| Experiment | Original start | New start | Original min # years | New min # years | 
| --- | ---| --- | --- | --- |
| esm-ssp585ext | 2100-> | 2101 | 201-> | 200 |
| esm-ssp585-ssp126Lu-ext  | 2100-> | 2101 | 201-> | 200 |

@charliepascoe

**Comment by durack1** [comment]
@dpkeller14 these changes are now in place, please double check all entries in [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any other issues
