### ISSUE TITLE
Model components and realms

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#604]
I have two questions about the model components and realms:

(1) How to the "components" referred to in the experiment_id CV relate (`AOGCM`, `AGCM`, etc) relate to components in the source_id CV (which match the realms: `atmos`, `ocean`, etc)?

(2) Do you know how these relate to ES-DOC model configurations (`ESMconfiguration`, `AOGCMconfiguration`)?

**Comment by taylor13** [comment]
I am not familiar with ESMconfiguration or AOGCMconfiguration, but the "components" in experiment_id generally refer to a source_type, which provides information on what processes are included in a model simulation.  Paul's note above points to the descriptions of each source_type.  Each experiment requires inclusion of a certain minimum set of processes, which determines the "required_model_components" referred to in the experiment_id CV.  It is also sometimes permissible to include certain additional components (the "additional_allowed_model_components").  

The same source_id (i.e., model) is associated with all the different configurations under which it is run.  So a single source_id may have different source_type designations, depending on the experiment.  (For example, the same source_id is associated both with AMIP runs and with coupled runs.)

In the source_id CV, "model_component"  simply lists all the individual components that may be activated.  The components are defined in terms of the "realm" they are primarily responsible for.  So an "atmospheric model component", will be responsible for all variables in the "atmos" realm.   Note that an AGCM calculates both atmospheric variables and land surface variables, so it would include at least "atmos" and  "land" model_components. 

The reason source_type isn't simply a list of the model_components (i.e. realms) is that we use source_type as a search facet, and we want users to be able, for example, to select "atmosphere-only" (i.e., AMIP-style) runs.  This can be done by selecting source_type = "AGCM".  If source_type were constructed from a list of realms, then selecting "atmos" would return both AGCM's and AOGCM's because both of these include an "atmos" component.

**Comment by durack1** [comment]
I might also add that the `source_type` is a CV see [CMIP6_source_type.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_type.json)

**Comment by martinjuckes** [comment]
Thanks .. I hadn't spotted the link to `source_type` (with hindsight, the `required_model_components` attribute of the `experiment_id` CV might be better labelled `required_source_types`). 

Although @taylor13 has commented on the reasons for having a vocabulary which is distinct from `realm`, the relationship between the two is still unclear to me (though there is a significant amount of information in the definitions). Here is a list of suggested relationships (where terms listed are required, unless there is a "?" to indicate that it is optional; "landIce[dynamic]" indicates that a specific type of landIce component is needed):

        "AER":["aerosol"],
        "AGCM":["atmos","land","landIce?"],
        "AOGCM":["atmos","ocean","land","seaIce?","landIce?"]
        "BGC": -- implies ocnBgchem when used with OGCM or AOGCM, no explicit realm for land and atmos;
        "CHEM": ["atmosChem"]
        "ISM": ["landIce[dynamic]"]
        "LAND": ["land","landIce?"]
        "OGCM":["ocean","seaIce?"]
        "RAD": -- no realm
        "SLAB": ["ocean[surface layer]"

Is that correct, as far as it goes?

**Comment by taylor13** [comment]
This looks to be correct, but if something critical depends on these relationships, I would like to double check.  

I would note that I know of no ocean models that don't include a sea-ice component, so possibly "seaIce?" should be replaced by "seaice".    And all land models I know of either include "landIce" or "landIce[dynamic]", so perhaps "landIce?" should be replaced by "landIce".

Also, source_type may be a list, so to cover all of these you would need to include entries like:
```
"AGCM CHEM": [["atmos","land","atmosChem,"landIce?"],
```

**Comment by taylor13** [comment]
possible correction:  not sure whether OMIP runs are with prescribed sea ice.  If so, then seaIce is not always paired with "ocean" and "OGCM":["ocean","seaIce?"] would be correct.

**Comment by martinjuckes** [comment]
Thanks. 

This is not of high importance at the moment, but could be important if we want to do something about making it possible to filter out parts of the Data Request which are irrelevant to certain experiments (a request from Sebastien). I don't see any immediate route to doing this at the moment, but would like to understand these relationships better in order to explore the possibilities. I would also like to give ES-DOC a prompt about consistency (following on from my question 2 in the initial post).

Taking an initial look through the ES-DOC model configurations, it looks as though they don't expect `land` without `landIce` or `ocean` without `seaIce`, so it may be OK to drop the question marks.

I'm hoping that the effect of combining source_types in a list will be to combine the lists of realms for the individual source_types.

**Comment by durack1** [comment]
@taylor13 @martinjuckes let me know if there are changes required here, from the discussion above it's not clear to me exactly what is suggested. If we plan to make changes, I recommend we outline these in detail in this issue and allow others watching this repo a couple of days to comment before implementing

**Comment by durack1** [comment]
@martinjuckes it's not clear that there is any action to be taken here, so I will close. If additional work is required please reopen and outline what steps are required
