### ISSUE TITLE
institution_id registration of NIMS-KMA

### ISSUE THREAD

**Issue by johanlee07** [WCRP-CMIP/CMIP6_CVs#67]
institution_id = NIMS-KMA
    institution = National Institute of Meteorological Sciences/Korea Meteorological Administration, Climate Research Division, Seoho-bukro 33, Seogwipo-si, Jejudo 63568, Republic of Korea

**Comment by davidhassell** [comment]
Hello,

My name is David Hassell and I am part of the ES-DOC team that is working on CMIP6 documentation. As a part of this process, we need a liaison at NIMS-KMA who can act as the interface between the scientists who actually provide the documentation and the ES-DOC team. I was wondering if you are able to help with identifying such a person?

The documentation process has changed considerably since CMIP5 (in response to the feedback that we received), and you can now choose from a variety of documentation methods. Our aim is to train the ES-DOC liaison who can then work with people at NIMS-KMA. No specialist knowledge about ES-DOC nor climate modelling is required, but neither would it be a problem, of course. Some institutes have appointed a member of the modelling team, others not.

I would be very grateful f you could let me know by e-mail (david.hassell at ncas.ac.uk) if you have any suggestions.

All the best,

David Hassell

National Centre for Atmospheric Science
University of Reading
UK

**Comment by johanlee07** [comment]
Dear David,

I think I’m the very person you are looking for. :)
If you need anything, please let me know.

Best regards,
Johan

**Comment by davidhassell** [comment]
Dear Johan,

Thank you very much, for offering to be the ES-DOC liaison for NIMS-KMA. It is greatly appreciated and we look forward to working with you. We are currently working on finalising the tools and resources that will be used during the documentation process, and will let you know as soon as we are ready. Until then, some background and overview information is available at [https://es-doc.org/cmip6]()

It would be very useful if we could have an e-mail address for you  - that will be our primary means of sending out information to ES-DOC liaisons from every institute, so it would be great if you send me a personal message to david.hassell at ncas.ac.uk

All the best,

David Hassell and Eric Guilyardi
