### ISSUE TITLE
Add CDRMIP to list of activities (MIPs) for UKESM1-0-LL

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#824]
Could `CDRMIP` please be added to the activity list for `UKESM1-0-LL`?

Code to make this change would be something like
```
source_id = json.load(open('CMIP6_source_id.json'))
source_id['source_id']['UKESM1-0-LL']['activity_participation'].append('CDRMIP')
source_id['source_id']['UKESM1-0-LL']['activity_participation'].sort()
```
TIA.

**Comment by durack1** [comment]
@matthew-mizielinski that change is now in place, so please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any other tweaks required.

As an aside, I have bolted all this together so that the versioning is managed by code, which means I make less mistakes - if you want to see the script take a peek at [`src/writeJson.py`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py) with your specific edit implemented on [lines 872-885](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py#L872-L885)

**Comment by matthew-mizielinski** [comment]
Thanks @durack1, looks good to me!
