### ISSUE TITLE
experiment_id -- how to publish emission driven variants of ScenarioMIP tier 1 experiments?

### ISSUE THREAD

**Issue by sol1105** [WCRP-CMIP/CMIP6_CVs#982]
Colleagues at the MPI-M conducted an ensemble of emission driven scenario simulations with their model MPI-ESM1-2-LR (between 10 to 30 members for each ssp585, _ssp245, ssp126 and ssp370_). However, the CMIP6-CV does only include esm-ssp585 as an emission driven variant of the four ScenarioMIP tier 1 experiments (ssp126, ssp245, ssp370 and ssp585). Also for the DAMIP/CovidMIP experiments, they conducted an ensemble of simulations that are emission driven (despite the experiment descriptions stating that the experiments are all concentration driven, #973 ).

My question is, how to publish this emission driven simulations as part of CMIP6 to the ESGF?
For example, two solutions would be to:
1) either include the emission driven variants of the above mentioned experiments to the CMIP6-CV
2) or to publish the emission driven simulations using the experiment_ids of their concentration driven variants, however, specifying global attributes (variant_info, comment, ...) and entries in the ES-DOC errata database that denote this runs are actually emission driven, as well as setting the forcing-index of the member-ids to a different value than the ones of the already published concentration driven simulations of the MPI-M.

How should one proceed in this matter? Are you aware of any similar cases (open issues or already published simulations)?

**Comment by durack1** [comment]
@sol1105 there is one emission-driven scenario that is sponsored by `C4MIP`, see [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) and search for `esm-ssp585`.

For the other experiments, this is a good question, how different are the emissions from the concentrations that are specified for `ssp245` etc?

@taylor13 ping

**Comment by taylor13** [comment]
@sol1105 The WGCM Infrastructure Panel (WIP) discussed this yesterday, and decided since these are not CMIP-endorsed MIP experiments, they cannot be hosted within the CMIP6 data archive.  

There may be alternatives for serving this data, which everyone agrees is valuable.  The WIP will respond more fully providing guidance on the options.

**Comment by matthew-mizielinski** [comment]
@sol1105, as @taylor13 noted we discussed this on Tuesday and adding these experiments would require them to be proposed by a MIP, with the expectation that several groups would perform them, and at this stage of CMIP6 we don't think this is feasible. Publishing these data under the equivalent concentration driven experiments is likely to lead to confusion for users of the data, even with an appropriate set of errata.

At this point in time I'd suggest you consider alternative means of publication as these data are valuable. I note here that PRIMAVERA have been supported by CEDA in publishing additional data for HighResMIP simulations (they constructed their own MIP tables) at https://esgf-index1.ceda.ac.uk/search/primavera-ceda/.  I'd suggest talking to your local ESGF node and exploring this option.

**Comment by sol1105** [comment]
Thank you all for your answers. I understand that for the scenario simulations it is too late to include them as new experiments within CMIP6 and hence we will, as suggested, discuss it internally at DKRZ in which way to publish them to the ESGF.  
Regarding the emissions for esm-ssp245/126/370, I was told, that they have been retrieved via input4MIPs, where they are available next to the concentrations of the respective concentration driven scenarios (just as it is the case for esm-ssp585).

Regarding the recently specified CovidMIP experiments, I was told by the modelers, that the emission-driven model setup has been discussed beforehand with the organizer @ChrisJones-MOHC . So would it be possible in at least the case of the emission driven CovidMIP scenarios, to add them to the CMIP6 CV?

**Comment by wachsylon** [comment]
Hi all,

I believe that this decision was made under pressure of time so it may not be as drastic as I interpret it. But I think it draws a picture of a strategy for how future CMIP6-close or related projects should be handled. 

I for myself always argued that participants of endorsed MIPs should be aware that it is necessary to share new experiments and variable requests for their MIPs with the "official" all requests collecting CMIP6 data request and CMIP6 CV. Is that changing now?

I assume that emission driven scenario experiments are very similar to the already defined scenario experiments. Why should they be findable and accessible in a different project than ScenarioMIP? Or, and even more important, a different project than CMIP6?  Why cant they be integrated in DAMIP so that at least we have a definition of these experiments within CMIP6? Is CMIP6 frozen, static, fix from now on?

I think from a user perspective it is confusing to search for HighResMIP in CMIP6 and for additional data in a PRIMAVERA project. We would have the same for the use case of comparing of emission driven and concentration driven.
HOWEVER, I could explain it if there is a new approach of data sharing of CMIP6-close projects.

I fear that

> at this stage of CMIP6

means never and not only for these experiments. Starting a new project in ESGF can reduce barriers to modeling groups such as data standards and quality assurance.  They will love it. When the first project exist, there is no going back. There is no reason for new CMIP6-like projects to get in contact with CMIP6-CV and DReq. Just open a new project in ESGF.

If the plan is, from now on, to exclude CMIP6 close projects from the "big" CMIP6, I understand that strategy as the extent of variables and experiments in CMIP6 has increased dramatically. However, I would like to know :)

Best, Fabi

**Comment by taylor13** [comment]
thanks for these thoughtful comments.  We will need a little time to discuss this with the WIP and the CMIP panel, since as you recognize, anything we choose to do will have implications and will set a precedent.  I will urge the panel members to read your comment above so they will be aware of the concerns and your suggestions.  Thanks very much.

**Comment by wachsylon** [comment]
Hi,

@ChrisJones-MOHC @taylor13 @matthew-mizielinski @durack1 

Can you react to that? MPI-M only performed emission-driven runs for COVID. They cannot participate with their runs in DAMIP if you do not add these experiments in the CV or allow publishing them as concentration driven and as member `*f2`.  If there was an agreement before, this should be clarified:

> Regarding the recently specified CovidMIP experiments, I was told by the modelers, that the emission-driven model setup has
> been discussed beforehand with the organizer. So would it be possible in at least the case of the emission driven CovidMIP
> scenarios, to add them to the CMIP6 CV?

Best,
Fabi

**Comment by ChrisJones-MOHC** [comment]
We were aware they would only do these runs emissions-driven, yes. But we did not want to define an entire new simulation name just for this model. Can they submit as a variant of the existing experiments? Models differ in how they treat aerosols, and ozone without needing new experiment names for example.

--
Dr Chris Jones
Research Fellow, Earth System and Mitigation Science Team
Met Office Hadley Centre, FitzRoy Road, Exeter, EX1 3PB, U.K.
Skype-for-business: +44 (0)330 1350427
E-mail: chris.d.jones@metoffice.gov.uk<mailto:chris.d.jones@metoffice.gov.uk>  ||  http://www.metoffice.gov.uk<http://www.metoffice.gov.uk/>  ||  https://publons.com/researcher/1281267/chris-jones/

**Comment by durack1** [comment]
@sol1105 we have been discussing this query during a WIP call and have a couple of questions:
1. The [CMIP6 `ssp245` experiment notes "Concentration-driven"](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L8243), I assume you have run an *emissions-driven* ssp245 experiment that has been contributed, and this is the simulation that your CovidMIP 2020-2024 simulations have been spawned off?
2. You noted that the emissions used in your `*ssp245` simulations are provided alongside the concentrations, how different are simulations using the *concentration* vs *emissions* configuration, does the 2020 annual mean look considerably different between sims?

A number of my other WIP colleagues may have questions to raise alongside those 2 above

**Comment by sol1105** [comment]
Thank you for your reply.

1. We are asking on behalf of the MPI-M, we (DKRZ) did not contribute to this simulations. They ran ~10 emission driven ssp245 simulations. Additionally they ran 10-11 Covid Baseline simulations, which are also emission driven ssp245 simulations branching of the same esm-hist simulations and running until 2050. Afaik the only difference between the old and new emission driven ssp245 simulations is the aerosol forcing they used. I will ask whether the updated aerosol forcing data has also been retrieved from input4MIPs.
2. The emissions and concentrations are provided via input4MIPs. For the simulations I checked (one already published common concentration driven ssp245, one emission driven Covid baseline simulation and one emission driven ssp245) the annual mean tas is about the same (+-0.1K).

**Comment by taylor13** [comment]
Reviewing the above, the MPI-ESM1-2-LR model has successfully published some esm-ssp585 runs, as called for under the C4MIP experiment design.  This is great.

As I understand it, the proposal is to publish some esm-ssp585-covid runs, but that experiment is not in the authorized covid suite.  All of the covid runs are ssp245 variants, not ssp585.  There are esm-ssp585 runs called for by C4MIP, but no covid variants on these runs is called for by anyone. 

It appears likely that only a single model will perform these experiments, and since they are based on ssp585, not ssp245, there will be no comparison with other models possible.  Thus, these runs do not seem to qualify for inclusion in the CMIP6 multi-model data archive.

I would suggest preparing the data according to CMIP6 specifications, but simply serving the data from an ftp site (or comparable).   This would make it easy to obtain and easy to use.  

Any counter-suggestions?

**Comment by sol1105** [comment]
This is not entirely correct, I maybe should have opened two separate issues.

- The MPI-M conducted an ensemble of emission driven scenarios (esm-ssp245,esm-ssp370,esm-ssp585,esm-ssp126) of which only the esm-ssp585 exists in the data request / CV.

- Then they conducted an ensemble of emission driven CovidMIP simulations (esm-ssp245 with [updated Covid Aerosol forcing](https://www.essoar.org/doi/10.1002/essoar.10504704.1) as baseline and branching thereof esm-ssp245-covid, esm-ssp245-cov-modgreen, esm-ssp245-cov-strgreen, esm-ssp245-cov-fossil).

**Comment by ChrisJones-MOHC** [comment]
Hi,

Basically I see these as slightly-non-conformant entries for ssp245-covid. MPI knew this when they performed them – we discussed during building the protocol that they wanted to run emissions-driven, but most groups would do concentration driven. From an analysis point of view we decided we were happy to include both.

In the same way some models simulate or prescribe aerosols, or ozone, this is true here for CO2. So is it possible to submit them as ssp245-covid simulations? But note the non-conformance regarding the CO2 forcing?

Chris

--
Dr Chris Jones
Research Fellow, Earth System and Mitigation Science Team
Met Office Hadley Centre, FitzRoy Road, Exeter, EX1 3PB, U.K.
Skype-for-business: +44 (0)330 1350427
E-mail: chris.d.jones@metoffice.gov.uk<mailto:chris.d.jones@metoffice.gov.uk>  ||  http://www.metoffice.gov.uk<http://www.metoffice.gov.uk/>  ||  https://publons.com/researcher/1281267/chris-jones/

**Comment by matthew-mizielinski** [comment]
Hi All,

I've had a chat with @ChrisJones-MOHC, and (following our discussion on the WIP telecon yesterday) suggest that the  `ssp245-cov*` experiments could be published using a forcing index of `99`  provided that the deviations from the experiment definition (i.e. the emissions driven forcings) are clearly documented within the forthcoming CovidMIP paper and an Errata. This should be  just about acceptable for these experiments as they are for a single, specific purpose.

If an esm equivalent of ssp245 is needed then I don't think the same methodology would be appropriate -- the ScenarioMIP runs have far broader use and having data from emissions driven models here could lead to confusion and potentially science errors. Any such data would therefore need to be published separately from CMIP6.

**Comment by taylor13** [comment]
Thank you @sol1105 for correcting my summary and making what runs were done quite clear.  I agree with @matthew-mizielinski 's suggestion to include the emission-driven ssp245-cov* runs with forcing index 99.  

As Matt says, the baseline emissions-driven ssp245 run (and other emission-driven ssp runs) should probably *not* be published as part of CMIP6 if we want to avoid confusion.

**Comment by sol1105** [comment]
Thank you all, I will forward this information to the modelers.
The esm-ssp* simulations, including the parent simulations of the CovidMIP runs, will then likely be published in a new ESGF project, that, apart from the experiment_ids and experiment description will have the same (meta)data standard as CMIP6.
